# Generated by Django 5.2.17 on 2026-09-30 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('ALL_MEMBERS', 'All members'), ('OFFICERS', 'Officers only'), ('EVERYONE', 'Everyone')], default='ALL_MEMBERS', max_length=15)),
                ('is_important', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_important', '-publish_at'],
                'permissions': [('manage_announcements', 'Publish announcements')],
                'abstract': False,
                'default_permissions': (),
                'indexes': [models.Index(fields=['audience', 'publish_at'], name='notifications_announce_live')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('publish_at')), _connector='OR'), name='announcement_expires_after_publish')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('LOAN', 'Loans'), ('SAVINGS', 'Savings'), ('INVESTMENT', 'Investments'), ('DIVIDEND', 'Dividends'), ('CLOSURE', 'Account closure'), ('APPROVAL', 'Pending approval'), ('SYSTEM', 'System')], default='SYSTEM', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Portal route, e.g. /member/loans/<id>.', max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('send_notifications', 'Send notifications to members')],
                'abstract': False,
                'default_permissions': (),
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notifications_unread')],
            },
        ),
    ]
