# Generated by Django 5.2.17 on 2026-10-01 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_seed_settings'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('LOAN', 'Loans'), ('SAVINGS', 'Savings'), ('INVESTMENT', 'Investments'), ('DIVIDEND', 'Dividends'), ('CLOSURE', 'Account closure'), ('APPROVAL', 'Pending approval'), ('MESSAGE', 'Message from the cooperative'), ('SYSTEM', 'System')], default='SYSTEM', max_length=15),
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('audience', models.CharField(choices=[('ALL_ACTIVE', 'All active members'), ('DEPARTMENT', 'Active members of a department'), ('SELECTED', 'Selected members')], max_length=15)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='configuration.department')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='broadcast',
            field=models.ForeignKey(blank=True, help_text="Set when the notification came from an officer's message to many members.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.broadcast'),
        ),
    ]
