# Generated by Django 5.2.17 on 2026-09-30 17:03

import apps.common.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
            ],
            options={
                'ordering': ['-value_date', '-created_at'],
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('ledger.transaction',),
        ),
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. CHRISTMAS or REGULAR.', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('REGULAR', 'Regular (continuous)'), ('CYCLE', 'Cycle (yearly contribution window)')], max_length=10)),
                ('cycle_start_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('cycle_end_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('payout_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expected_monthly_contribution', apps.common.fields.MoneyField(default=0)),
                ('min_contribution', apps.common.fields.MoneyField(default=0)),
                ('allow_contribution_outside_window', models.BooleanField(default=False)),
                ('allow_multiple_contributions_per_period', models.BooleanField(default=False)),
                ('min_membership_months', models.PositiveSmallIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Opened automatically for every new member.')),
                ('allow_officer_withdrawal', models.BooleanField(default=False)),
                ('allow_member_withdrawal_request', models.BooleanField(default=False, help_text='Also requires the global setting. Off for EMDI.')),
                ('counts_toward_loan_eligibility', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'abstract': False,
                'default_permissions': (),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cycle_end_month__isnull', False), ('cycle_start_month__isnull', False), ('kind', 'CYCLE')), models.Q(('cycle_end_month__isnull', True), ('cycle_start_month__isnull', True), ('kind', 'REGULAR'), ('payout_month__isnull', True)), _connector='OR'), name='savings_product_cycle_window_matches_kind'), models.CheckConstraint(condition=models.Q(('cycle_start_month__isnull', True), ('cycle_start_month__lte', models.F('cycle_end_month')), _connector='OR'), name='savings_product_cycle_start_before_end'), models.CheckConstraint(condition=models.Q(models.Q(('cycle_start_month__isnull', True), ('cycle_start_month__range', (1, 12)), _connector='OR'), models.Q(('cycle_end_month__isnull', True), ('cycle_end_month__range', (1, 12)), _connector='OR'), models.Q(('payout_month__isnull', True), ('payout_month__range', (1, 12)), _connector='OR')), name='savings_product_months_valid'), models.CheckConstraint(condition=models.Q(('expected_monthly_contribution__gte', 0), ('min_contribution__gte', 0)), name='savings_product_amounts_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='SavingsCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_monthly_contribution', apps.common.fields.MoneyField(default=0)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('OPEN', 'Open for contributions'), ('CLOSED', 'Closed'), ('PAID_OUT', 'Paid out')], default='UPCOMING', max_length=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(limit_choices_to={'kind': 'CYCLE'}, on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='savings.savingsproduct')),
            ],
            options={
                'ordering': ['-year', 'product__display_order'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('elected_monthly_amount', apps.common.fields.MoneyField(blank=True, help_text="Member's chosen monthly amount; blank uses the product/cycle default.", null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('opened_on', models.DateField(default=django.utils.timezone.localdate)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_accounts', to='members.member')),
                ('cycle', models.ForeignKey(blank=True, help_text='Set for cycle products only (validated in the service layer).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='savings.savingscycle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='savings.savingsproduct')),
            ],
            options={
                'ordering': ['product__display_order', '-opened_on'],
                'permissions': [('view_savings', 'View savings'), ('manage_savings_products', 'Configure savings products'), ('manage_savings_cycles', 'Create and open savings cycles'), ('close_savings_cycle', 'Close savings cycles'), ('post_savings_contribution', 'Post savings contributions'), ('post_savings_withdrawal', 'Post savings withdrawals and cycle payouts')],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='savingscycle',
            constraint=models.UniqueConstraint(fields=('product', 'year'), name='savings_cycle_unique_product_year'),
        ),
        migrations.AddConstraint(
            model_name='savingscycle',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='savings_cycle_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='savingscycle',
            constraint=models.CheckConstraint(condition=models.Q(('expected_monthly_contribution__gte', 0)), name='savings_cycle_expected_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('cycle__isnull', True)), fields=('member', 'product'), name='savings_account_one_regular_per_member_product'),
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('cycle__isnull', False)), fields=('member', 'cycle'), name='savings_account_one_per_member_cycle'),
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.CheckConstraint(condition=models.Q(('elected_monthly_amount__isnull', True), ('elected_monthly_amount__gte', 0), _connector='OR'), name='savings_account_elected_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_on__isnull', False), ('status', 'CLOSED')), models.Q(models.Q(('status', 'CLOSED'), _negated=True), ('closed_on__isnull', True)), _connector='OR'), name='savings_account_closed_on_matches_status'),
        ),
    ]
