# Generated by Django 5.2.17 on 2026-10-02 04:49

import apps.common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_christmas_not_loan_collateral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyContributionChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', apps.common.fields.MoneyField()),
                ('effective_from', models.DateField(help_text='First day of the first month this amount applies to.')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribution_changes', to='savings.savingsaccount')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account', '-effective_from'],
                'abstract': False,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('account', 'effective_from'), name='contribution_change_one_per_month'), models.CheckConstraint(condition=models.Q(('effective_from__day', 1)), name='contribution_change_starts_a_month'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='contribution_change_amount_not_negative')],
            },
        ),
    ]
