# Generated by Django 5.2.17 on 2026-10-04 22:45

import apps.common.fields
from decimal import Decimal

from django.db import migrations


def set_regular_maximum(apps, schema_editor):
    # A sensible ceiling for the payroll deduction; officers can change it under Savings > Products.
    apps.get_model("savings", "SavingsProduct").objects.filter(code="REGULAR", max_monthly_contribution__isnull=True).update(
        max_monthly_contribution=Decimal("1000000.00")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_monthly_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsproduct',
            name='max_monthly_contribution',
            field=apps.common.fields.MoneyField(blank=True, help_text='Highest monthly contribution a member may choose (statutory product). Blank means no limit.', null=True),
        ),
        migrations.RunPython(set_regular_maximum, migrations.RunPython.noop),
    ]
