# Generated by Django 5.2.17 on 2026-09-30 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_repr', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(help_text='Dotted event name, e.g. loan.approved.', max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{field: [old, new]}')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system jobs and anonymous events such as failed logins.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-id'],
                'permissions': [('view_audit_log', 'View the audit log')],
                'default_permissions': (),
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_log_object'), models.Index(fields=['actor', 'timestamp'], name='audit_log_actor'), models.Index(fields=['action', 'timestamp'], name='audit_log_action')],
            },
        ),
    ]
