# Generated by Django 5.2.17 on 2026-09-30 17:03

import apps.common.fields
import apps.common.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDividend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basis_amount', apps.common.fields.MoneyField()),
                ('rate', apps.common.fields.RateField()),
                ('gross_amount', apps.common.fields.MoneyField()),
                ('withholding_amount', apps.common.fields.MoneyField(default=0)),
                ('net_amount', apps.common.fields.MoneyField()),
                ('calculation_detail', models.JSONField(default=dict, help_text='Inputs used, e.g. the month-end balances behind an average.')),
                ('status', models.CharField(choices=[('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('WITHHELD', 'Withheld')], default='CALCULATED', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['member__last_name', 'member__first_name'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DividendCalculationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_number', models.PositiveSmallIntegerField()),
                ('parameters', models.JSONField(default=dict)),
                ('total_basis', apps.common.fields.MoneyField(default=0)),
                ('total_gross', apps.common.fields.MoneyField(default=0)),
                ('total_withholding', apps.common.fields.MoneyField(default=0)),
                ('total_net', apps.common.fields.MoneyField(default=0)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Awaiting approval'), ('SUPERSEDED', 'Superseded by a later run'), ('APPROVED', 'Approved')], default='DRAFT', max_length=10)),
                ('run_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cycle', '-run_number'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DividendCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('financial_year', models.PositiveSmallIntegerField()),
                ('basis', models.CharField(choices=[('CLOSING_BALANCE', 'Balance at cutoff date'), ('AVERAGE_MONTHLY_BALANCE', 'Average month-end balance'), ('MINIMUM_BALANCE', 'Lowest month-end balance')], default='AVERAGE_MONTHLY_BALANCE', max_length=25)),
                ('cutoff_date', models.DateField()),
                ('rate', apps.common.fields.RateField(help_text='Dividend rate as a percentage.')),
                ('distributable_surplus', apps.common.fields.MoneyField(blank=True, help_text='Optional ceiling: total gross dividends must not exceed it.', null=True)),
                ('withholding_rate', apps.common.fields.RateField(default=0)),
                ('payment_method', models.CharField(choices=[('CREDIT_TO_SAVINGS', 'Credit to savings account'), ('EXTERNAL', 'Paid externally (bank/cash)')], default='CREDIT_TO_SAVINGS', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published to members'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dividends.dividendcalculationrun')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-financial_year'],
                'permissions': [('view_dividends', 'View dividend cycles'), ('manage_dividend_cycles', 'Create and configure dividend cycles'), ('calculate_dividends', 'Run dividend calculations'), ('approve_dividends', 'Approve and publish dividend cycles'), ('pay_dividends', 'Pay approved dividends')],
                'abstract': False,
                'default_permissions': (),
            },
            bases=(apps.common.models.ReferenceMixin, models.Model),
        ),
    ]
