# Generated by Django 5.2.17 on 2026-09-30 17:03

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dividends', '0001_initial'),
        ('investments', '0001_initial'),
        ('ledger', '0001_initial'),
        ('members', '0001_initial'),
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendcycle',
            name='credit_savings_product',
            field=models.ForeignKey(blank=True, help_text='Savings product credited when paying by CREDIT_TO_SAVINGS.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='savings.savingsproduct'),
        ),
        migrations.AddField(
            model_name='dividendcycle',
            name='eligible_investment_products',
            field=models.ManyToManyField(blank=True, related_name='dividend_cycles', to='investments.investmentproduct'),
        ),
        migrations.AddField(
            model_name='dividendcycle',
            name='eligible_savings_products',
            field=models.ManyToManyField(blank=True, related_name='dividend_cycles', to='savings.savingsproduct'),
        ),
        migrations.AddField(
            model_name='dividendcycle',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dividendcalculationrun',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='dividends.dividendcycle'),
        ),
        migrations.AddField(
            model_name='memberdividend',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_dividends', to='dividends.dividendcycle'),
        ),
        migrations.AddField(
            model_name='memberdividend',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividends', to='members.member'),
        ),
        migrations.AddField(
            model_name='memberdividend',
            name='payment_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_dividend', to='ledger.transaction'),
        ),
        migrations.AddField(
            model_name='memberdividend',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_dividends', to='dividends.dividendcalculationrun'),
        ),
        migrations.AddConstraint(
            model_name='dividendcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('financial_year',), name='dividend_cycle_one_live_per_year'),
        ),
        migrations.AddConstraint(
            model_name='dividendcycle',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0)), name='dividend_cycle_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='dividendcycle',
            constraint=models.CheckConstraint(condition=models.Q(('withholding_rate__gte', 0), ('withholding_rate__lte', 100)), name='dividend_cycle_withholding_range'),
        ),
        migrations.AddConstraint(
            model_name='dividendcycle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_method', 'CREDIT_TO_SAVINGS'), _negated=True), ('credit_savings_product__isnull', False), _connector='OR'), name='dividend_cycle_credit_product_required'),
        ),
        migrations.AddConstraint(
            model_name='dividendcycle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['APPROVED', 'PUBLISHED', 'PAID']), _negated=True), models.Q(('approved_by__isnull', False), ('approved_run__isnull', False)), _connector='OR'), name='dividend_cycle_approval_recorded'),
        ),
        migrations.AddConstraint(
            model_name='dividendcalculationrun',
            constraint=models.UniqueConstraint(fields=('cycle', 'run_number'), name='dividend_run_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='dividendcalculationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APPROVED')), fields=('cycle',), name='dividend_run_one_approved_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='dividendcalculationrun',
            constraint=models.CheckConstraint(condition=models.Q(('total_net', django.db.models.expressions.CombinedExpression(models.F('total_gross'), '-', models.F('total_withholding')))), name='dividend_run_net_equals_gross_less_withholding'),
        ),
        migrations.AddIndex(
            model_name='memberdividend',
            index=models.Index(fields=['member', 'cycle'], name='dividends_member_cycle'),
        ),
        migrations.AddConstraint(
            model_name='memberdividend',
            constraint=models.UniqueConstraint(fields=('run', 'member'), name='member_dividend_unique_per_run'),
        ),
        migrations.AddConstraint(
            model_name='memberdividend',
            constraint=models.CheckConstraint(condition=models.Q(('basis_amount__gte', 0), ('gross_amount__gte', 0), ('withholding_amount__gte', 0)), name='member_dividend_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='memberdividend',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount', django.db.models.expressions.CombinedExpression(models.F('gross_amount'), '-', models.F('withholding_amount')))), name='member_dividend_net_equals_gross_less_withholding'),
        ),
        migrations.AddConstraint(
            model_name='memberdividend',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAID'), _negated=True), models.Q(('paid_at__isnull', False), ('payment_transaction__isnull', False)), _connector='OR'), name='member_dividend_paid_has_transaction'),
        ),
    ]
