# Generated by Django 5.2.17 on 2026-09-30 17:03

import apps.common.fields
import apps.common.models
import apps.common.uploads
import apps.common.validators
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('amount_requested', apps.common.fields.MoneyField()),
                ('term_months', models.PositiveSmallIntegerField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('RETURNED', 'Returned for more information'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('DISBURSED', 'Disbursed')], default='DRAFT', max_length=15)),
                ('eligibility_snapshot', models.JSONField(blank=True, default=dict, help_text='Eligibility check results recorded at submission.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Internal; never shown to the member.')),
                ('info_request_message', models.TextField(blank=True, help_text='Shown to the member when returned.')),
                ('approved_amount', apps.common.fields.MoneyField(blank=True, null=True)),
                ('approved_term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True, help_text='Shown to the member.')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='members.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': (),
            },
            bases=(apps.common.models.ReferenceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LoanApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to=apps.common.uploads.loan_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.common.validators.validate_file_size])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loanapplication')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('interest_rate', apps.common.fields.RateField(help_text='Percentage, e.g. 10.0000 for 10%.')),
                ('interest_rate_basis', models.CharField(choices=[('PER_ANNUM', 'Per annum'), ('PER_LOAN', 'Flat for the whole term'), ('PER_MONTH', 'Per month')], default='PER_ANNUM', max_length=10)),
                ('interest_method', models.CharField(choices=[('FLAT', 'Flat'), ('REDUCING_BALANCE', 'Reducing balance')], default='FLAT', max_length=20)),
                ('interest_collection', models.CharField(choices=[('AMORTISED', 'Repaid with instalments'), ('UPFRONT', 'Deducted at disbursement')], default='AMORTISED', max_length=10)),
                ('min_amount', apps.common.fields.MoneyField(default=0)),
                ('max_amount', apps.common.fields.MoneyField()),
                ('max_savings_multiple', models.DecimalField(blank=True, decimal_places=2, help_text="Loan may not exceed this multiple of the member's eligible savings. Blank = no rule.", max_digits=5, null=True)),
                ('min_term_months', models.PositiveSmallIntegerField(default=1)),
                ('max_term_months', models.PositiveSmallIntegerField()),
                ('allowed_terms', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, help_text='Specific terms offered (months). Empty = any term within the range.', size=None)),
                ('min_membership_months', models.PositiveSmallIntegerField(default=0)),
                ('max_active_loans', models.PositiveSmallIntegerField(default=1, help_text='Active loans of this product a member may hold at once.')),
                ('guarantors_required', models.PositiveSmallIntegerField(default=0)),
                ('required_documents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, size=None)),
                ('allow_topup', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'default_permissions': (),
                'constraints': [models.CheckConstraint(condition=models.Q(('interest_rate__gte', 0)), name='loan_product_rate_non_negative'), models.CheckConstraint(condition=models.Q(('min_amount__gte', 0), ('max_amount__gt', 0), ('min_amount__lte', models.F('max_amount'))), name='loan_product_amount_range'), models.CheckConstraint(condition=models.Q(('min_term_months__gte', 1), ('min_term_months__lte', models.F('max_term_months'))), name='loan_product_term_range'), models.CheckConstraint(condition=models.Q(('max_savings_multiple__isnull', True), ('max_savings_multiple__gt', 0), _connector='OR'), name='loan_product_savings_multiple_positive')],
            },
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loans.loanproduct'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('principal', apps.common.fields.MoneyField()),
                ('interest_rate', apps.common.fields.RateField()),
                ('interest_rate_basis', models.CharField(choices=[('PER_ANNUM', 'Per annum'), ('PER_LOAN', 'Flat for the whole term'), ('PER_MONTH', 'Per month')], max_length=10)),
                ('interest_method', models.CharField(choices=[('FLAT', 'Flat'), ('REDUCING_BALANCE', 'Reducing balance')], max_length=20)),
                ('interest_collection', models.CharField(choices=[('AMORTISED', 'Repaid with instalments'), ('UPFRONT', 'Deducted at disbursement')], max_length=10)),
                ('term_months', models.PositiveSmallIntegerField()),
                ('total_interest', apps.common.fields.MoneyField(default=0)),
                ('disbursed_on', models.DateField()),
                ('first_due_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted'), ('WRITTEN_OFF', 'Written off')], default='ACTIVE', max_length=12)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('defaulted_on', models.DateField(blank=True, null=True)),
                ('is_migrated', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='members.member')),
                ('application', models.OneToOneField(blank=True, help_text='Blank only for loans migrated from the previous records at go-live.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loans.loanapplication')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-disbursed_on', '-created_at'],
                'permissions': [('view_loans', 'View loans and applications'), ('manage_loan_products', 'Configure loan products'), ('review_loan_application', 'Review loan applications'), ('approve_loan_application', 'Approve or reject loan applications'), ('disburse_loan', 'Disburse approved loans'), ('record_loan_repayment', 'Record loan repayments'), ('mark_loan_default', 'Mark loans as defaulted')],
                'abstract': False,
                'default_permissions': (),
            },
            bases=(apps.common.models.ReferenceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_component', apps.common.fields.MoneyField(default=0)),
                ('interest_component', apps.common.fields.MoneyField(default=0)),
                ('penalty_component', apps.common.fields.MoneyField(default=0)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loan')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayment', to='ledger.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RepaymentInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', apps.common.fields.MoneyField()),
                ('interest_due', apps.common.fields.MoneyField(default=0)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='loans.loan')),
            ],
            options={
                'ordering': ['loan', 'number'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RepaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_amount', apps.common.fields.MoneyField(default=0)),
                ('interest_amount', apps.common.fields.MoneyField(default=0)),
                ('repayment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='loans.loanrepayment')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='loans.repaymentinstallment')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_guaranteed', apps.common.fields.MoneyField()),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantors', to='loans.loanapplication')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantees', to='members.member')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('application', 'guarantor'), name='loan_guarantor_unique'), models.CheckConstraint(condition=models.Q(('amount_guaranteed__gt', 0)), name='loan_guarantor_amount_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['member', 'status'], name='loans_application_member'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['status', 'submitted_at'], name='loans_application_queue'),
        ),
        migrations.AddConstraint(
            model_name='loanapplication',
            constraint=models.CheckConstraint(condition=models.Q(('amount_requested__gt', 0)), name='loan_application_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='loanapplication',
            constraint=models.CheckConstraint(condition=models.Q(('term_months__gte', 1)), name='loan_application_term_positive'),
        ),
        migrations.AddConstraint(
            model_name='loanapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['APPROVED', 'DISBURSED']), _negated=True), models.Q(('approved_amount__gt', 0), ('approved_term_months__gte', 1), ('decided_by__isnull', False)), _connector='OR'), name='loan_application_approval_recorded'),
        ),
        migrations.AddConstraint(
            model_name='loanapplication',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('submitted_at__isnull', False), ('status', 'CANCELLED'), _connector='OR'), name='loan_application_submitted_at_set'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['member', 'status'], name='loans_loan_member_status'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'maturity_date'], name='loans_loan_status_maturity'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('principal__gt', 0)), name='loan_principal_positive'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('interest_rate__gte', 0)), name='loan_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('total_interest__gte', 0)), name='loan_interest_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('term_months__gte', 1)), name='loan_term_positive'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('first_due_date__gte', models.F('disbursed_on')), ('maturity_date__gte', models.F('first_due_date'))), name='loan_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('application__isnull', False), ('is_migrated', True), _connector='OR'), name='loan_has_application_unless_migrated'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_on__isnull', False), _connector='OR'), name='loan_completed_on_set'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DEFAULTED'), _negated=True), ('defaulted_on__isnull', False), _connector='OR'), name='loan_defaulted_on_set'),
        ),
        migrations.AddConstraint(
            model_name='loanrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('principal_component__gte', 0), ('interest_component__gte', 0), ('penalty_component__gte', 0)), name='loan_repayment_components_non_negative'),
        ),
        migrations.AddIndex(
            model_name='repaymentinstallment',
            index=models.Index(fields=['due_date'], name='loans_installment_due'),
        ),
        migrations.AddConstraint(
            model_name='repaymentinstallment',
            constraint=models.UniqueConstraint(fields=('loan', 'number'), name='loan_installment_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='repaymentinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='loan_installment_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='repaymentinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('principal_due__gte', 0), ('interest_due__gte', 0)), name='loan_installment_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='repaymentallocation',
            constraint=models.UniqueConstraint(fields=('repayment', 'installment'), name='loan_allocation_unique'),
        ),
        migrations.AddConstraint(
            model_name='repaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gte', 0), ('interest_amount__gte', 0)), name='loan_allocation_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='repaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gt', 0), ('interest_amount__gt', 0), _connector='OR'), name='loan_allocation_not_empty'),
        ),
    ]
