# Generated by Django 5.2.17 on 2026-09-30 19:29

import apps.common.uploads
import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationdocument',
            name='file',
            field=models.FileField(upload_to=apps.common.uploads.loan_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.common.validators.validate_file_size, apps.common.validators.validate_file_signature]),
        ),
    ]
