# Generated by Django 5.2.17 on 2026-09-30 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loanapplicationdocument_file'),
        ('members', '0002_member_import_and_upload_checks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Blank only for loans migrated from the previous records at go-live.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loanapplication'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING_DISBURSEMENT', 'Disbursement awaiting approval'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted'), ('WRITTEN_OFF', 'Written off'), ('CANCELLED', 'Cancelled (disbursement rejected)')], default='PENDING_DISBURSEMENT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('application',), name='loan_one_live_loan_per_application'),
        ),
        migrations.AddConstraint(
            model_name='loanproduct',
            constraint=models.CheckConstraint(condition=models.Q(('interest_method', 'REDUCING_BALANCE'), ('interest_rate_basis', 'PER_LOAN'), _negated=True), name='loan_product_reducing_needs_periodic_rate'),
        ),
    ]
