# Generated by Django 5.2.17 on 2026-10-01 19:03

import apps.common.fields
from django.db import migrations, models


def require_one_guarantor(apps, schema_editor):
    """BR-28: every loan needs at least one guarantor. Products set to 0 move to 1."""
    apps.get_model("loans", "LoanProduct").objects.filter(guarantors_required=0).update(guarantors_required=1)


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_disbursement_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanguarantor',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='requested_at',
            field=models.DateTimeField(blank=True, help_text='When the guarantor was asked (notified); empty while the application is a draft.', null=True),
        ),
        migrations.AlterField(
            model_name='loanguarantor',
            name='amount_guaranteed',
            field=apps.common.fields.MoneyField(help_text="This guarantor's share of the amount requested."),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='guarantors_required',
            field=models.PositiveSmallIntegerField(default=1, help_text='Guarantors (fellow members) each application needs. At least one (BR-28).'),
        ),
        migrations.RunPython(require_one_guarantor, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='loanproduct',
            constraint=models.CheckConstraint(condition=models.Q(('guarantors_required__gte', 1)), name='loan_product_needs_a_guarantor'),
        ),
    ]
