# Generated by Django 5.2.17 on 2026-09-30 17:03

import apps.common.fields
import apps.common.models
import apps.common.uploads
import apps.common.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closures', '0002_initial'),
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('batch_type', models.CharField(choices=[('CONTRIBUTIONS', 'Savings contributions'), ('LOAN_REPAYMENTS', 'Loan repayments'), ('OPENING_BALANCES', 'Opening balances'), ('INVESTMENTS', 'Investment contributions'), ('DIVIDEND_PAYMENTS', 'Dividend payments'), ('CYCLE_PAYOUTS', 'Savings cycle payouts')], max_length=30)),
                ('period', models.DateField(blank=True, help_text='First day of the month the batch relates to.', null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source_file', models.FileField(blank=True, upload_to=apps.common.uploads.batch_source_path, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'csv']), apps.common.validators.validate_file_size])),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('total_amount', apps.common.fields.MoneyField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('SUBMITTED', 'Submitted for approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'transaction batches',
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': (),
            },
            bases=(apps.common.models.ReferenceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('txn_type', models.CharField(choices=[('SAVINGS_OPENING_BALANCE', 'Savings opening balance'), ('SAVINGS_CONTRIBUTION', 'Savings contribution'), ('SAVINGS_WITHDRAWAL', 'Savings withdrawal'), ('SAVINGS_CYCLE_PAYOUT', 'Savings cycle payout'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('LOAN_INTEREST_CHARGE', 'Loan interest charge'), ('LOAN_PENALTY', 'Loan penalty'), ('LOAN_REPAYMENT', 'Loan repayment'), ('INVESTMENT_OPENING_BALANCE', 'Investment opening balance'), ('INVESTMENT_CONTRIBUTION', 'Investment contribution'), ('INVESTMENT_LIQUIDATION', 'Investment liquidation'), ('DIVIDEND_PAYMENT', 'Dividend payment'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal')], max_length=40)),
                ('entry_side', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('amount', apps.common.fields.MoneyField()),
                ('value_date', models.DateField(default=django.utils.timezone.localdate)),
                ('period', models.DateField(blank=True, help_text='First day of the month this entry counts for (contributions, repayments).', null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('external_reference', models.CharField(blank=True, help_text='Payroll run, bank teller or receipt number.', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='PENDING', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closure_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_transactions', to='closures.accountclosurerequest')),
                ('created_by', models.ForeignKey(blank=True, help_text='Null only for system-generated entries.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='investments.investmentaccount')),
            ],
            options={
                'ordering': ['-value_date', '-created_at'],
                'permissions': [('view_all_transactions', "View all members' transactions"), ('approve_transaction', 'Approve or reject pending transactions'), ('reverse_transaction', 'Reverse posted transactions'), ('post_adjustment', 'Create adjustment entries'), ('manage_batches', 'Upload and submit transaction batches'), ('approve_batch', 'Approve transaction batches')],
                'abstract': False,
                'default_permissions': (),
            },
            bases=(apps.common.models.ReferenceMixin, models.Model),
        ),
    ]
