# Generated by Django 5.2.17 on 2026-09-30 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('loans', '0001_initial'),
        ('members', '0001_initial'),
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='members.member'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reverses',
            field=models.OneToOneField(blank=True, help_text='The entry this REVERSAL cancels. An entry can be reversed only once.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='ledger.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='savings_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='savings.savingsaccount'),
        ),
        migrations.AddField(
            model_name='transactionbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.transactionbatch'),
        ),
        migrations.AddConstraint(
            model_name='transactionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('created_by')), _negated=True), _connector='OR'), name='ledger_batch_maker_checker'),
        ),
        migrations.AddConstraint(
            model_name='transactionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('period__isnull', True), ('period__day', 1), _connector='OR'), name='ledger_batch_period_first_of_month'),
        ),
        migrations.AddConstraint(
            model_name='transactionbatch',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='ledger_batch_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['member', 'value_date'], name='ledger_txn_member_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['savings_account', 'status'], name='ledger_txn_savings_status'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['loan', 'status'], name='ledger_txn_loan_status'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['investment_account', 'status'], name='ledger_txn_invest_status'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['txn_type', 'value_date'], name='ledger_txn_type_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='ledger_txn_status_created'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['period'], name='ledger_txn_period'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_txn_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('investment_account__isnull', True), ('loan__isnull', True), ('savings_account__isnull', False)), models.Q(('investment_account__isnull', True), ('loan__isnull', False), ('savings_account__isnull', True)), models.Q(('investment_account__isnull', False), ('loan__isnull', True), ('savings_account__isnull', True)), models.Q(('investment_account__isnull', True), ('loan__isnull', True), ('savings_account__isnull', True), ('txn_type', 'DIVIDEND_PAYMENT')), _connector='OR'), name='ledger_txn_exactly_one_account'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('savings_account__isnull', False), ('txn_type__in', ['SAVINGS_OPENING_BALANCE', 'SAVINGS_CONTRIBUTION', 'SAVINGS_WITHDRAWAL', 'SAVINGS_CYCLE_PAYOUT'])), models.Q(('loan__isnull', False), ('txn_type__in', ['LOAN_DISBURSEMENT', 'LOAN_INTEREST_CHARGE', 'LOAN_PENALTY', 'LOAN_REPAYMENT'])), models.Q(('investment_account__isnull', False), ('txn_type__in', ['INVESTMENT_OPENING_BALANCE', 'INVESTMENT_CONTRIBUTION', 'INVESTMENT_LIQUIDATION'])), models.Q(('investment_account__isnull', True), ('loan__isnull', True), ('txn_type', 'DIVIDEND_PAYMENT')), ('txn_type__in', ['ADJUSTMENT', 'REVERSAL']), _connector='OR'), name='ledger_txn_type_matches_account'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('txn_type__in', ['ADJUSTMENT', 'REVERSAL']), models.Q(('entry_side', 'CREDIT'), ('txn_type__in', ['SAVINGS_OPENING_BALANCE', 'SAVINGS_CONTRIBUTION', 'LOAN_REPAYMENT', 'INVESTMENT_OPENING_BALANCE', 'INVESTMENT_CONTRIBUTION', 'DIVIDEND_PAYMENT'])), models.Q(('entry_side', 'DEBIT'), ('txn_type__in', ['SAVINGS_WITHDRAWAL', 'SAVINGS_CYCLE_PAYOUT', 'LOAN_DISBURSEMENT', 'LOAN_INTEREST_CHARGE', 'LOAN_PENALTY', 'INVESTMENT_LIQUIDATION'])), _connector='OR'), name='ledger_txn_type_side'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('period__isnull', True), ('period__day', 1), _connector='OR'), name='ledger_txn_period_first_of_month'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reverses__isnull', False), ('txn_type', 'REVERSAL')), models.Q(models.Q(('txn_type', 'REVERSAL'), _negated=True), ('reverses__isnull', True)), _connector='OR'), name='ledger_txn_reversal_link'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('created_by')), _negated=True), _connector='OR'), name='ledger_txn_maker_checker'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('posted_at__isnull', False), ('status__in', ['POSTED', 'REVERSED'])), models.Q(('posted_at__isnull', True), ('status__in', ['PENDING', 'REJECTED'])), _connector='OR'), name='ledger_txn_posted_at_matches_status'),
        ),
    ]
