# Generated by Django 5.2.17 on 2026-09-30 19:29

import apps.common.uploads
import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_append_only_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionbatch',
            name='source_file',
            field=models.FileField(blank=True, upload_to=apps.common.uploads.batch_source_path, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'csv']), apps.common.validators.validate_file_size, apps.common.validators.validate_file_signature]),
        ),
    ]
