# Generated by Django 5.2.17 on 2026-09-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_transactionbatch_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionbatch',
            name='batch_type',
            field=models.CharField(choices=[('CONTRIBUTIONS', 'Savings contributions'), ('LOAN_REPAYMENTS', 'Loan repayments'), ('OPENING_BALANCES', 'Savings opening balances'), ('INVESTMENTS', 'Investment contributions'), ('INVESTMENT_OPENING_BALANCES', 'Investment opening balances'), ('DIVIDEND_PAYMENTS', 'Dividend payments'), ('CYCLE_PAYOUTS', 'Savings cycle payouts')], max_length=30),
        ),
    ]
