# Generated by Django 5.2.17 on 2026-10-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_investment_batch_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionbatch',
            name='batch_type',
            field=models.CharField(choices=[('CONTRIBUTIONS', 'Savings contributions'), ('LOAN_REPAYMENTS', 'Loan repayments'), ('OPENING_BALANCES', 'Savings opening balances'), ('INVESTMENTS', 'Investment contributions'), ('INVESTMENT_OPENING_BALANCES', 'Investment opening balances'), ('DIVIDEND_PAYMENTS', 'Dividend payments'), ('CYCLE_PAYOUTS', 'Savings cycle payouts'), ('CLOSURE_SETTLEMENT', 'Account closure settlement')], max_length=30),
        ),
    ]
