# Generated by Django 5.2.17 on 2026-09-30 17:03

import apps.common.uploads
import apps.common.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closures', '0001_initial'),
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('title', models.CharField(blank=True, choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MISS', 'Miss'), ('MS', 'Ms'), ('DR', 'Dr'), ('ENGR', 'Engr'), ('PROF', 'Prof')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('residential_address', models.TextField(blank=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=50)),
                ('lga', models.CharField(blank=True, max_length=100, verbose_name='LGA')),
                ('photo', models.ImageField(blank=True, upload_to=apps.common.uploads.member_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), apps.common.validators.validate_file_size])),
                ('staff_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('ippis_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='IPPIS number')),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('grade_level', models.CharField(blank=True, max_length=20)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'In service'), ('RETIRED', 'Retired'), ('TRANSFERRED', 'Transferred'), ('RESIGNED', 'Resigned'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=15)),
                ('date_joined', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('PENDING', 'Pending activation'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='PENDING', max_length=10)),
                ('status_reason', models.CharField(blank=True, max_length=255)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=10)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='configuration.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'permissions': [('view_member', 'View member records'), ('add_member', 'Register members'), ('change_member', 'Edit member records'), ('import_members', 'Import members from a spreadsheet'), ('change_member_status', 'Activate, suspend, reinstate or deactivate members'), ('manage_member_documents', 'Upload and verify member documents')],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('PASSPORT_PHOTO', 'Passport photograph'), ('ID_CARD', 'Identity card'), ('APPOINTMENT_LETTER', 'Appointment letter'), ('SIGNATURE', 'Signature specimen'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(upload_to=apps.common.uploads.member_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.common.validators.validate_file_size])),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MembershipStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('PENDING', 'Pending activation'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], max_length=10)),
                ('to_status', models.CharField(choices=[('PENDING', 'Pending activation'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closure_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='closures.accountclosurerequest')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='members.member')),
            ],
            options={
                'verbose_name_plural': 'next of kin',
                'ordering': ['-is_primary', 'full_name'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='members_member_status'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='members_member_name'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', False), ('status', 'CLOSED')), models.Q(models.Q(('status', 'CLOSED'), _negated=True), ('closed_at__isnull', True)), _connector='OR'), name='members_member_closed_at_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='nextofkin',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('member',), name='members_one_primary_next_of_kin'),
        ),
    ]
