# Generated by Django 5.2.17 on 2026-09-30 19:29

import apps.common.models
import apps.common.uploads
import apps.common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.common.uploads.member_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), apps.common.validators.validate_file_size, apps.common.validators.validate_file_signature]),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='file',
            field=models.FileField(upload_to=apps.common.uploads.member_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.common.validators.validate_file_size, apps.common.validators.validate_file_signature]),
        ),
        migrations.CreateModel(
            name='MemberImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('source_file', models.FileField(upload_to=apps.common.uploads.member_import_path, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'csv']), apps.common.validators.validate_file_size, apps.common.validators.validate_file_signature])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('READY', 'Validated, ready to commit'), ('HAS_ERRORS', 'Has errors'), ('COMMITTED', 'Committed')], max_length=12)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('rows', models.JSONField(blank=True, default=list, help_text='Normalised row data committed on approval.')),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'default_permissions': (),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMMITTED'), _negated=True), models.Q(('committed_at__isnull', False), ('committed_by__isnull', False)), _connector='OR'), name='member_import_commit_recorded')],
            },
            bases=(apps.common.models.ReferenceMixin, models.Model),
        ),
    ]
