# Generated by Django 5.2.17 on 2026-09-30 17:03

import apps.common.uploads
import apps.configuration.models
import django.contrib.postgres.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CooperativeSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='EMDI Cooperative Society', max_length=200)),
                ('short_name', models.CharField(default='EMDI Coop', max_length=50)),
                ('parent_institution', models.CharField(default='Engineering Materials Development Institute (EMDI), NASENI', max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('logo', models.ImageField(blank=True, upload_to=apps.common.uploads.cooperative_logo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('currency_code', models.CharField(default='NGN', max_length=3)),
                ('membership_number_format', models.CharField(default='EMDI/COOP/{seq:04d}', help_text='Python format string; {seq} is the next number, {year} the current year.', max_length=50)),
                ('financial_year_start_month', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('dividend_processing_month', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('member_withdrawal_requests_enabled', models.BooleanField(default=False, help_text='Global switch. While off, no savings product can accept member withdrawal requests.')),
                ('closure_disables_portal_login', models.BooleanField(default=True)),
                ('maker_checker_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SAVINGS_OPENING_BALANCE', 'Savings opening balance'), ('SAVINGS_CONTRIBUTION', 'Savings contribution'), ('SAVINGS_WITHDRAWAL', 'Savings withdrawal'), ('SAVINGS_CYCLE_PAYOUT', 'Savings cycle payout'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('LOAN_INTEREST_CHARGE', 'Loan interest charge'), ('LOAN_PENALTY', 'Loan penalty'), ('LOAN_REPAYMENT', 'Loan repayment'), ('INVESTMENT_OPENING_BALANCE', 'Investment opening balance'), ('INVESTMENT_CONTRIBUTION', 'Investment contribution'), ('INVESTMENT_LIQUIDATION', 'Investment liquidation'), ('DIVIDEND_PAYMENT', 'Dividend payment'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal')], max_length=40), blank=True, default=apps.configuration.models.default_maker_checker_types, help_text='Transaction types that must be approved by a second officer before posting.', size=None)),
                ('loan_overdue_grace_days', models.PositiveSmallIntegerField(default=7)),
                ('session_idle_timeout_minutes', models.PositiveSmallIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cooperative settings',
                'verbose_name_plural': 'cooperative settings',
                'permissions': [('manage_settings', 'Manage cooperative settings')],
                'default_permissions': (),
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='cooperative_settings_singleton')],
            },
        ),
    ]
