# Generated by Django 5.2.17 on 2026-10-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_seed_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativesettings',
            name='contributions_tracked_from',
            field=models.DateField(blank=True, help_text="First month that monthly contribution arrears are counted from. Blank counts from when each member's savings account was opened.", null=True),
        ),
    ]
