# Generated by Django 5.2.17 on 2026-10-05 00:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_monthly_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativesettings',
            name='guarantor_savings_multiple',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('2.00'), help_text='A member may guarantee loans totalling at most this multiple of their savings. Blank means no limit.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
