# Generated by Django 5.2.17 on 2026-09-30 17:03

import apps.common.models
import apps.common.uploads
import apps.common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClosureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('reason_category', models.CharField(choices=[('RETIREMENT', 'Retirement'), ('RESIGNATION', 'Resignation from service'), ('TRANSFER', 'Transfer'), ('PERSONAL', 'Personal reasons'), ('OTHER', 'Other')], max_length=15)),
                ('reason', models.TextField()),
                ('additional_information', models.TextField(blank=True)),
                ('confirmed', models.BooleanField(help_text='Member confirmed they understand the consequences of closing their account.')),
                ('attachment', models.FileField(blank=True, upload_to=apps.common.uploads.closure_attachment_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.common.validators.validate_file_size])),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed'), ('WITHDRAWN', 'Withdrawn by member')], default='SUBMITTED', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Internal; never shown to the member.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True, help_text='Shown to the member.')),
                ('settlement_statement', models.JSONField(blank=True, default=dict, help_text='Balances and net position frozen at approval.')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_closure_requests', 'View account closure requests'), ('review_closure_request', 'Review account closure requests'), ('approve_closure_request', 'Approve or reject account closure requests'), ('execute_account_closure', 'Settle and close approved accounts')],
                'abstract': False,
                'default_permissions': (),
            },
            bases=(apps.common.models.ReferenceMixin, models.Model),
        ),
    ]
