# Generated by Django 5.2.17 on 2026-09-30 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closures', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountclosurerequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closure_requests', to='members.member'),
        ),
        migrations.AddField(
            model_name='accountclosurerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accountclosurerequest',
            index=models.Index(fields=['status', 'created_at'], name='closures_request_queue'),
        ),
        migrations.AddConstraint(
            model_name='accountclosurerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SUBMITTED', 'UNDER_REVIEW', 'APPROVED'])), fields=('member',), name='closure_one_open_request_per_member'),
        ),
        migrations.AddConstraint(
            model_name='accountclosurerequest',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed', True)), name='closure_request_confirmed'),
        ),
        migrations.AddConstraint(
            model_name='accountclosurerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['APPROVED', 'REJECTED', 'CLOSED']), _negated=True), ('decided_by__isnull', False), _connector='OR'), name='closure_request_decision_recorded'),
        ),
        migrations.AddConstraint(
            model_name='accountclosurerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CLOSED'), _negated=True), models.Q(('closed_at__isnull', False), ('closed_by__isnull', False)), _connector='OR'), name='closure_request_closure_recorded'),
        ),
    ]
