# Generated by Django 5.2.17 on 2026-09-30 19:29

import apps.common.uploads
import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountclosurerequest',
            name='attachment',
            field=models.FileField(blank=True, upload_to=apps.common.uploads.closure_attachment_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.common.validators.validate_file_size, apps.common.validators.validate_file_signature]),
        ),
    ]
