# Generated by Django 5.2.17 on 2026-09-30 17:03

import apps.common.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('opened_on', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('LIQUIDATED', 'Liquidated'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('closed_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-opened_on'],
                'permissions': [('view_investments', 'View investments'), ('manage_investment_products', 'Configure investment products'), ('manage_investment_accounts', 'Open and close investment accounts'), ('post_investment_transaction', 'Post investment contributions, liquidations and returns')],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InvestmentProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_amount', apps.common.fields.MoneyField(default=0)),
                ('lock_in_months', models.PositiveSmallIntegerField(blank=True, help_text='Months before liquidation is allowed. Blank = none.', null=True)),
                ('dividend_eligible', models.BooleanField(default=True)),
                ('allow_officer_liquidation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InvestmentReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.PositiveSmallIntegerField()),
                ('amount_earned', apps.common.fields.MoneyField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-financial_year', 'product__name'],
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
