# Generated by Django 5.2.17 on 2026-09-30 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        ('ledger', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
            ],
            options={
                'ordering': ['-value_date', '-created_at'],
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('ledger.transaction',),
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_accounts', to='members.member'),
        ),
        migrations.AddConstraint(
            model_name='investmentproduct',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__gte', 0)), name='investment_product_min_non_negative'),
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='investments.investmentproduct'),
        ),
        migrations.AddField(
            model_name='investmentreturn',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='investments.investmentproduct'),
        ),
        migrations.AddField(
            model_name='investmentreturn',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='investmentaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('member', 'product'), name='investment_account_one_active_per_product'),
        ),
        migrations.AddIndex(
            model_name='investmentreturn',
            index=models.Index(fields=['financial_year'], name='investments_return_year'),
        ),
    ]
