# Generated by Django 5.0.3 on 2026-03-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_rename_total_value_shareaccount_current_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetransaction',
            name='number_of_shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
