/** Choice lists mirrored from the backend models, as [value, label] pairs. */
export const MEMBER_STATUS = [['PENDING', 'Pending'], ['ACTIVE', 'Active'], ['SUSPENDED', 'Suspended'], ['INACTIVE', 'Inactive'], ['CLOSED', 'Closed']];
export const TITLES = [['MR', 'Mr'], ['MRS', 'Mrs'], ['MISS', 'Miss'], ['MS', 'Ms'], ['DR', 'Dr'], ['ENGR', 'Engr'], ['PROF', 'Prof']];
export const GENDERS = [['MALE', 'Male'], ['FEMALE', 'Female']];
export const MARITAL = [['SINGLE', 'Single'], ['MARRIED', 'Married'], ['DIVORCED', 'Divorced'], ['WIDOWED', 'Widowed']];
export const EMPLOYMENT = [['ACTIVE', 'In service'], ['RETIRED', 'Retired'], ['TRANSFERRED', 'Transferred'], ['RESIGNED', 'Resigned'], ['DECEASED', 'Deceased']];
export const DOCUMENT_TYPES = [['PASSPORT_PHOTO', 'Passport photograph'], ['ID_CARD', 'ID card'], ['APPOINTMENT_LETTER', 'Appointment letter'], ['SIGNATURE', 'Signature'], ['OTHER', 'Other']];

export const CLOSURE_STATUS = [['SUBMITTED', 'Submitted'], ['UNDER_REVIEW', 'Under review'], ['APPROVED', 'Approved'], ['REJECTED', 'Rejected'], ['CLOSED', 'Closed'], ['WITHDRAWN', 'Withdrawn']];

export const SAVINGS_KIND = [['REGULAR', 'Regular savings'], ['CYCLE', 'Cycle savings (e.g. Christmas)']];
export const CYCLE_STATUS = [['UPCOMING', 'Upcoming'], ['OPEN', 'Open'], ['CLOSED', 'Closed'], ['PAID_OUT', 'Paid out']];
export const SAVINGS_ACCOUNT_STATUS = [['ACTIVE', 'Active'], ['FROZEN', 'Frozen'], ['CLOSED', 'Closed']];

export const APPLICATION_STATUS = [['SUBMITTED', 'Submitted'], ['UNDER_REVIEW', 'Under review'], ['RETURNED', 'Returned'], ['APPROVED', 'Approved'], ['REJECTED', 'Rejected'], ['CANCELLED', 'Cancelled'], ['DISBURSED', 'Disbursed']];
export const LOAN_STATUS = [['PENDING_DISBURSEMENT', 'Pending disbursement'], ['ACTIVE', 'Active'], ['COMPLETED', 'Completed'], ['DEFAULTED', 'Defaulted'], ['WRITTEN_OFF', 'Written off'], ['CANCELLED', 'Cancelled']];
export const RATE_BASIS = [['PER_ANNUM', 'Per year'], ['PER_MONTH', 'Per month'], ['PER_LOAN', 'For the whole loan']];
export const INTEREST_METHOD = [['FLAT', 'Flat'], ['REDUCING_BALANCE', 'Reducing balance']];
export const INTEREST_COLLECTION = [['AMORTISED', 'With each instalment'], ['UPFRONT', 'Deducted at disbursement']];

export const INVESTMENT_STATUS = [['ACTIVE', 'Active'], ['MATURED', 'Matured'], ['LIQUIDATED', 'Liquidated'], ['CLOSED', 'Closed']];

export const DIVIDEND_STATUS = [['DRAFT', 'Draft'], ['CALCULATED', 'Calculated'], ['APPROVED', 'Approved'], ['PUBLISHED', 'Published'], ['PAID', 'Paid'], ['CANCELLED', 'Cancelled']];
export const DIVIDEND_BASIS = [['CLOSING_BALANCE', 'Closing balance at cut-off'], ['AVERAGE_MONTHLY_BALANCE', 'Average monthly balance'], ['MINIMUM_BALANCE', 'Minimum monthly balance']];
export const DIVIDEND_PAYMENT = [['CREDIT_TO_SAVINGS', 'Credit to a savings account'], ['EXTERNAL', 'Pay out externally (bank transfer)']];

export const TXN_STATUS = [['PENDING', 'Pending'], ['POSTED', 'Posted'], ['REJECTED', 'Rejected'], ['REVERSED', 'Reversed']];
export const TXN_TYPES = [
  ['SAVINGS_OPENING_BALANCE', 'Savings opening balance'], ['SAVINGS_CONTRIBUTION', 'Savings contribution'], ['SAVINGS_WITHDRAWAL', 'Savings withdrawal'],
  ['SAVINGS_CYCLE_PAYOUT', 'Cycle savings payout'], ['LOAN_DISBURSEMENT', 'Loan disbursement'], ['LOAN_INTEREST_CHARGE', 'Loan interest charge'],
  ['LOAN_PENALTY', 'Loan penalty'], ['LOAN_REPAYMENT', 'Loan repayment'], ['INVESTMENT_OPENING_BALANCE', 'Investment opening balance'],
  ['INVESTMENT_CONTRIBUTION', 'Investment contribution'], ['INVESTMENT_LIQUIDATION', 'Investment liquidation'], ['DIVIDEND_PAYMENT', 'Dividend payment'],
  ['ADJUSTMENT', 'Adjustment'], ['REVERSAL', 'Reversal'],
];
export const BATCH_STATUS = [['DRAFT', 'Draft'], ['VALIDATED', 'Validated'], ['SUBMITTED', 'Submitted'], ['APPROVED', 'Approved'], ['POSTED', 'Posted'], ['REJECTED', 'Rejected']];
// Batch types an officer can upload as a spreadsheet; the others are generated by the system.
export const UPLOAD_BATCH_TYPES = [
  ['CONTRIBUTIONS', 'Savings contributions'], ['LOAN_REPAYMENTS', 'Loan repayments'], ['INVESTMENTS', 'Investment contributions'],
  ['OPENING_BALANCES', 'Savings opening balances'], ['INVESTMENT_OPENING_BALANCES', 'Investment opening balances'],
];
export const BATCH_TYPES = [
  ...UPLOAD_BATCH_TYPES, ['CYCLE_PAYOUTS', 'Cycle savings payouts'], ['DIVIDEND_PAYMENTS', 'Dividend payments'], ['CLOSURE_SETTLEMENT', 'Account closure settlement'],
];

export const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'].map((m, i) => [i + 1, m]);

export const label = (choices, value) => choices.find(([v]) => v === value)?.[1] || value;

/** <option> elements for a choice list. */
export const options = (choices) => choices.map(([v, l]) => <option key={v} value={v}>{l}</option>);

/** First day of the current month as YYYY-MM (for period inputs). */
export const currentPeriod = () => new Date().toISOString().slice(0, 7);
export const today = () => {
  const d = new Date();
  return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 10);
};

export const ANNOUNCEMENT_AUDIENCE = [['ALL_MEMBERS', 'All members'], ['OFFICERS', 'Officers only'], ['EVERYONE', 'Everyone']];
export const ANNOUNCEMENT_STATE = [['LIVE', 'Live'], ['SCHEDULED', 'Scheduled'], ['ENDED', 'Ended']];
export const BROADCAST_AUDIENCE = [['ALL_ACTIVE', 'All active members'], ['DEPARTMENT', 'Active members of a department'], ['SELECTED', 'Selected members']];
